  # mkdocs.yml
   markdown_extensions:
     - attr_list
   plugins:
     - mkdocs-video:
         is_video: True
         video_muted: True
         video_controls: True
         css_style:
           width: "100%"
